name: PushAction

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - .github/workflows/pullrequest.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Cancel previous runs
        uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: philips-software/sonar-scanner-action@master
        with:
          url: ${{ secrets.SONARQUBE_HOST }}
          token: ${{ secrets.SONARQUBE_TOKEN }}
          projectKey: jekyll-link-checker
          projectName: Jekyll Link Checker

      - name: Cleanup scan
        run: sudo rm -rf "$GITHUB_WORKSPACE/.scannerwork"

      - name: Determine image tag
        run: |
          IMAGE_TAG=$(echo "${{ github.event.after }}" | cut -c 1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build container image
        run: |
          cd $GITHUB_WORKSPACE
          # Do some magic to figure out what our base image is
          IFS=' ' read -ra FOO <<< $(grep "FROM" Dockerfile)
          # Make sure we have the latest Ubuntu base image
          docker pull ${FOO[1]}
          # and then build our container.
          docker build --force-rm --build-arg bamboo_build=$IMAGE_TAG -t "linaroits/linkcheck:$IMAGE_TAG" .

      - name: Publish container image
        run: |
          docker tag linaroits/linkcheck:$IMAGE_TAG linaroits/linkcheck:latest
          docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker push linaroits/linkcheck:latest
          docker push linaroits/linkcheck:$IMAGE_TAG

      - name: Clean up images
        run: |
          docker rmi linaroits/linkcheck:latest
          docker rmi linaroits/linkcheck:$IMAGE_TAG
